---
- name: This playbook to download a war file from nexus
  hosts: localhost
  become: true

  tasks:
    - name: download war file
      shell: 'curl -u admin:Vbgy0r!23 -X GET -L "http://44.201.109.126:8081/service/rest/v1/search/assets/download?sort=version&repository=ssvkart5devops-SNAPSHOT&maven.groupId=com.ssvkart5lab&maven.artifactId=ssvkart5devops&maven.extension=war" -H "accept: application/json" --output /home/ansibleadmin/latest.war'
        
      args:
        chdir: /home/ansibleadmin

- name: Deploy the latest war file to load apache tomcat
  hosts : webservers
  become: true

  tasks:
    - copy: 
        src: "{{ item }}"
        dest: "/opt/apache-tomcat-9.0.68/webapps/"
      with_fileglob:
        - "/home/ansibleadmin/*.war"

...

